import Layout from "@/components/Layout";
import { useEffect } from "react";

export default function PrivacyPolicy() {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <Layout>
      <div className="min-h-screen bg-white dark:bg-[#0a0a0a]">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white py-12">
          <div className="container">
            <h1 className="text-4xl font-black mb-2">Privacy Policy</h1>
            <p className="text-blue-100">Effective Date: July 1, 2026</p>
          </div>
        </div>

        {/* Content */}
        <div className="container py-12">
          <div className="max-w-4xl mx-auto">
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>PRIVACY POLICY</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Gravity Co., Ltd. (“Company,” “we”, “us” or “our”) maintains this Privacy Policy (“Privacy Policy”) that summarizes our policies and processes on how we collect, use disclose, transfer and store your personal information. The Privacy Policy applies only to the collection, use and storage of personal information that you may decide to provide to us in your use of: (1) our website(s) (our “Sites”), (2) our applications for mobile platforms or devices and our web applications accessible on social networking services (“SNS”) (collectively, our mobile and web applications are referred to herein as, the “Applications”), (3) our game publisher networks, crowd sourcing service and platforms (collectively, “Networks”) provided in connection with Applications and third-party applications utilizing our Services (“Third Party Mobile Applications”) and (4) chat rooms, blogs, web forums, messaging boards or other public forums in Applications and our Sites (collectively, our “Forums”).  The Applications, Networks, Sites and Forums are referred to herein collectively, as the “Services”. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">By accepting our Privacy Policy and the applicable Terms of Service during Service account registration or by otherwise accessing or using our Service(s) you are agreeing to the terms and conditions of this Privacy Policy (including our collection, storage, use and disclosure of your personal information) and that your access or use of the Service(s) is also subject to the applicable Terms of Service.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}><strong>Notwithstanding any provision herein, under any circumstance, the countries embargoed by the United States or the countries set forth on “the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce Denied Persons List or Entity List” shall be clearly excluded from the scope of any services.</strong></p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '0px'}}>1. Collecting Personal Information</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Our primary goal in collecting the information described below is to provide you, the user, with a customized experience on our Service and to deliver better service, products, and more relevant content to our customers, prospective customers, and visitors.   </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">1) Personal Information We Collect</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Personal information may be collected from you during your use of the Service, including, during (a) the registration process, (b) promotional campaigns, (c) customer support and technical service requests, and/or (d) ordering and use of products and other services, or from and through third party service providers and partners.  </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Information Collected Directly From You </strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Registration Information.</u>  When you communicate directly with us, either through an Application, at our Site, a Network or Forum, you are authorizing us to collect, store and use/share information collected from you in accordance with this Privacy Policy.  Such information may include: (i) your age or birthday; (ii) your first and last name; (iii) your valid e-mail address and telephone number; (iv) password and other information necessary to ensure security of your account; and (v) such other information you choose to provide to us such as billing information, profile photo, photo representation (avatar), character name, interests and hobbies, game play preferences, and links to profiles on various SNS.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">From time to time we may expand or change the information requested upon registration or log-in, so this may not be a complete list.  We ask that you provide only your own personal information, not personal information concerning anyone else.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Usage Information.</u> We collect details of your use of our Services and the resources that you access. Such usage information include information about how and when you access or use our Services (such as Games accessed, game score, pages visited, purchase and use of Virtual Money and/or Virtual Goods, the details of your purchases, and your game play).</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Interaction and Communications among Users.</u> We collect information about (i) your interaction with other users (for example, invite, gift, sharing of your rank or level, screen-shots, etc.) and (ii) your communication and interaction with your contacts through social media channels (including, social network services, messengers, and any other services which has social features like invite friends and sharing information with friends).</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Information Through Mobile Devices.</u>  When you use an Application or Third Party Mobile Application on your mobile telephone or other mobile devices (“Mobile Device”), in addition to such information described above, you are authorizing us to collect, store and use/share the following information (as applicable): (i) Mobile Device type; (ii) mobile carrier; (iii) Internet Protocol address; (iv) geographic location/country; (v) platform version; (vi) navigation, interaction and engagement information regarding our users (vii) MAC address, International Mobile Equipment Identity (IMEI), display resolution, time and date on screen of Mobile Devices and; (viii) such other information you choose to provide to us. In addition, we receive and store information you provide when you sign up to have Short Message Service (“SMS”) notifications set directly to your Mobile Device.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Payment and Billing Information.</u>  If you purchase any in-Service items, our third party partners will collect the payment and billing information necessary to complete the transaction.  Such information may include: (i) your first and last name; (ii) your valid e-mail address; (iii) credit card, PayPal and other third party payment processor information; (iv) billing address; and (v) such other information you choose to provide.  Our third party partner may also receive the foregoing information that you provide when you purchase Applications and Third Party Mobile Applications through your Mobile Device.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Customer Service and Support.</u>  When you send email or other communications to us in connection with customer service and support, we will collect and store your contact information, information about your use of the Service, your user ID and such other information you provide to us in order to process your inquiries, respond to your requests and improve our Service.  We will also store the correspondence and any information contained therein.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>Profile Information.</u>  We provide areas on our Service where you can post information about yourself and others and communicate with others or upload content such as photographs. Such postings are governed by the applicable Terms of Service. In addition, such postings may appear on other websites or services, or when searches are executed on the subject of your posting. Also, whenever you voluntarily disclose personal information on publicly-viewable areas, that information will be publicly available and can be collected and used by others. For example, if you post your email address, you may receive unsolicited messages. We cannot control who reads your posting or what other users may do with the information you voluntarily post, so we encourage you to exercise discretion and caution with respect to your personal information. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Informa</strong><strong>tion Received from SNS and APIs</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">When you use an Application at an SNS, you allow us to access certain information from your profile through such SNS and the applicable SNS platform Application Programming Interface (“API”).  The information we receive varies by the Application and by the privacy settings you choose for the SNS and may include any or all of the following information, as allowed by you, the SNS and your privacy preferences: (i) your first and last name; (ii) your profile picture or its URL; (iii) your user ID number; which is linked to publicly available information such as name and profile photo; (iv) the user ID numbers for your friends that are also connected to our Application(s); (v) login e-mail you provided to the SNS when you registered; (vi) your physical location and that of your access device(s) and (vii) your gender.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">By using our Application(s) through an SNS, you are authorizing us to collect, store and use/share any and all information you agreed the SNS could disclose to us through the API in accordance with this Privacy Policy.  Your agreement is evidenced when you “accept” or “allow” (or comparable terms) one of our Applications on an SNS.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>2) </strong><strong>How </strong><strong>We Collect Personal Information</strong></p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Automated Information Collection Technol</strong><strong>ogies</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">As described below, when you access our Services, we collect certain technical information and may associate such information with your user or account ID number for our internal use.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Cookies </strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">A “cookie” is a small text file that is sent to your browser from a web server and stored on your computer’s hard drive.  We may use cookies to track general, non-personal information about our users (e.g., user name, pages viewed, time spent on our Site(s), games, and the sites visited just before and just after our Site(s)) for statistical and market research purposes.    </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We use cookies to gather information about our users’ browser activities in order to constantly improve our Service.  This information assists us to design and arrange our web pages in a most user-friendly manner and to continually improve our Service to better meet the needs of our customers, prospective customers, and visitors.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We may also use local shared objects known as “flash cookies”, which help us to prevent fraud, remember your in-game settings and to track your progress on certain in-game tasks.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You have choices with respect to cookies.  By modifying your browser preferences, you have the option to reject all cookies, or limit the type of cookies you allow.  Flash cookies operate differently from browser cookies and cookie management tools available in a web browser will not remove flash cookies.  To learn more about and manage flash cookies you can visit www.adobe.com Rejecting or limiting the type of cookies may, however, in limited instances prevent you from accessing certain features on our Service.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Log Files</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Like most Internet services, we may also use log files on the server side.  The data held in log files includes your computer’s or Mobile Device’s IP (Internet Protocol) address, browser type, browser language, e-mail application, Internet service provider, referring/exit Web pages, computer platform type, date/time stamp, and user activity.  Company uses server log data to analyze trends, administer the services offered through our Service.  We and our third party partners may use this information for product and service improvements, and in marketing and advertising services.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The software enabling our Services has associated log and temporary files that are stored on Company’s servers.  These files store your account information, preference settings, system notifications as well as other data necessary to enable you to participate on our Service.  Your information may also exist within regularly performed server backups.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Tracking Technologies</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Our Services may utilize a variety of methods for tracking purposes, including web beacons (also known as Internet tags, pixel tags and clear GIFs).  Web beacons are small pieces of data that are embedded in images on the pages of websites to analyze the traffic patterns, such as the frequency users visit various areas of our Services.  Pixel tags may allow us to advertise more efficiently by excluding our current users from certain promotional messages or identifying the source of a new installation.  These methods may involve transmitting information either directly to us or to another entity authorized by us to collect information on our behalf.  We also use these technical methods in HTML e-mails that we send our guests to determine whether our guests have opened those e-mails or clicked on links in those e-mails.  With web beacon technology, the information that we collect and share is anonymous and not personally identifiable. It does not contain your name, address, telephone number, or email address. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Third Party Advertisers</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Many advertisements are managed and placed on the service by third parties. These third party advertisers may use cookies, web beacons or similar automated information collection technologies on your computer or Mobile Devices to help present, better target, and measure the effectiveness of their advertisements, by collecting non-personally identifiable information when you click on or move your cursor over one of their advertisements.  We may share certain non-personally identifiable information about you as a user with certain third party advertisers to help them deliver more relevant advertisements through their ad networks.  In some cases, we may have access to information from cookies, web beacons and similar automated information collection technologies used by third party advertisers on our Services and this information may permit us to identify other sites or services that you have visited that are also associated with the third party advertiser.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The use of cookies, web beacons, or similar automated information collection technologies by third party advertisers is subject to their own privacy policies.  Finally, once you have clicked on an advertisement and have left the Service, our Privacy Policy no longer applies and you must read the privacy policy of the applicable third party advertiser to see how your personal information will be collected, stored and used as part of their service.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Click Through URLs</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Some of our Services, including email messages, use “click-through URLs” linked to other content on our Services.  We track this click-through data to help us determine interest in topics and use of the Services.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Monitoring/Public Information</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You may also choose to disclose personal information in our Forums.  Personal information you disclose in such Forums is public information, and there is no expectation of privacy or confidentiality.  Please refer to the Terms of Service for additional information relating to the disclosure of personal information in such Forums.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Other Sources</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}>We may collect or receive information from other sources including other users of the Service and third party information providers and partners.  For example, we receive and store the information you provide when you enter any promotion, sweepstakes or loyalty program.  Such information may be used to supplement your account information and/or profile and may be combined with other information we collect from you.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">2. Use, Disclosure and Transfer</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Unless otherwise described elsewhere in this Privacy Policy, we will not use or disclose any personal information collected from you.  Your personal information may be used alone or in the aggregate with information collected from other users.  </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Use by Company</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We use the information you provide so that we may better understand your needs and the needs of our customers, prospective customers, and visitors.  Specifically, we use your personal information for many purposes, including:</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(a) 	to allow you to register for and use our Services;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(b)	to apply for employment opportunities at the Company;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(c)	to audit and analyze data to improve and ensure the continued smooth operation of our Service;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(d) 	for market research purposes, including, without limitation, to analyze user characteristics and usage patterns in order to better understand how our Services are used and market them more effectively;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(e) 	to communicate with you concerning your account or to send you announcements, newsletters, promotional materials and other information about our Services or offerings of our business partners, and to offer you opportunities to participate in surveys, contest and sweepstakes; *</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(f)  	to prevent or investigate actual or suspected fraud, hacking, infringement, or other misconduct involving our Service;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(g)  	to respond to inquiries, troubleshoot problems, investigate incidents, and handle complaints; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(h) 	provide, maintain, protect and improve our Services, including keeping you posted on our latest Service announcements, software updates and upcoming events, and develop new services; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(i)	protect our rights or property or that of our users; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(j)	 to satisfy any applicable law, regulation, legal process or enforceable government request;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(k)	to send notices, such as communications about your purchases and changes to our Terms of Service, this Privacy Policy and other Service-specific policies, and to enforce applicable terms and conditions set forth in such policies; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(l)	to enable user-to-user communications; and</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(m)	protect against harm to the rights, property or safety of the Company, its users or the public as required or permitted by law.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Company processes personal information on our databases, equipment and servers (owned by the Company and/or third parties in the South Korea and in other countries).  In some cases, we may process personal information outside of your country.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">*If you decide at any time that you no longer wish to receive such communications from us, please follow the unsubscribe instructions provided in any of the communications or follow the process described in the “Opt-Out Provision” section below</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Disclosure and Tra</strong><strong>nsfer to Third Parties</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We generally do not disclose or transfer any personal information about our customers, prospects, or visitors to any third parties.  We may however, disclose and transfer data which does not contain or reveal any personally identifiable information or is specifically attributable to you to our business partners, third party analytics service providers, ad networks and advertisers (collectively, “Partners”).  Provided, however, some Partners may also act as third party service providers (described below) to us and may have access to your personally identifiable information. Moreover, Partners may obtain public information about you from your profile or other public sources.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We may also periodically engage in co-marketing activities, where we work with a complementary solution provider to launch a joint marketing program.  In these situations, we will only send information to you on behalf of the other; we do not provide your personally identifiable information to such partner.  We may also enter into business partnerships with other parties to provide specific services.  If a user signs up for these services or responds to a particular marketing offer, we may share personally identifiable information such as your name or other contact information that is necessary for our business partner to provide these services or get in contact with you.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Disclosure of your personally identifiable information may occur when we engage or employ service providers, vendors or other third parties to facilitate the provision of our Services (including, without limitation, payment processing, data analysis, e-mail delivery, hosting services, customer service and promotional services) to provide the Services on our behalf, or to assist us in analyzing how our Services are being used.  Such third party service provider ( “Third Party Partner”) may have access to your personally identifiable information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Currently, the name of Third Party Partner, services performed by it on our behalf, service territory of it, and period of retention and use by it of Personal Information are as follows:</p>
            <div className="overflow-x-auto my-4">
              <table className="w-full border-collapse border border-gray-400 dark:border-gray-600 text-sm">
            <thead>
              <tr>
              <th className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-left font-semibold bg-gray-100 dark:bg-gray-800 text-sm">Name</th>
              <th className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-left font-semibold bg-gray-100 dark:bg-gray-800 text-sm">Data Storage Place</th>
              <th className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-left font-semibold bg-gray-100 dark:bg-gray-800 text-sm">Transferred Data</th>
              <th className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-left font-semibold bg-gray-100 dark:bg-gray-800 text-sm">Relevant Contract</th>
              </tr>
            </thead>
            <tbody>
              <tr>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Gala Lab Corp.</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Seoul, Korea</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">User ID, Game account information, In-game activity logs</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Game development for Ragnarok Universe</td>
              </tr>
              <tr>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Wemade Connect Corp.</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Seoul, Korea</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">User ID, Personal information, Payment history, Item logs, Customer support records</td>
              <td className="border border-gray-400 dark:border-gray-600 px-3 py-2 text-sm">Operation of Ragnarok Universe and Personal Information Management</td>
              </tr>
            </tbody>
              </table>
            </div>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">In the event Company combines with another company in the future through a corporate merger, sale, acquisition, liquidation or other similar process, your personally identifiable information may be transferred with the business or a part of it, or may be sold as an asset of the business, to the successor organization in such transaction.  If material changes to the Company’s privacy practices will occur as a result of such transaction, we will notify you and other users in the manner described in this Privacy Policy.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">In addition, upon the expiration or a termination of any third party license arrangements involving one or more parts of the Service, your personal information (including name, email address and other personally identifiable information) may be transferred to the subject third party licensor in accordance with the terms of the applicable license agreement.  In advance of such transfer to a third party licensor, the Company will notify you and other users in writing in the manner described in this Privacy Policy.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Safety, Security an</strong><strong>d Legally Required Disclosures </strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Your personally identifiable information, and communications you make within the Service, may be accessed and disclosed if we believe that our Service is being used in the commission of a crime, when we believe in good faith that there is an emergency that poses a threat to the safety of you or another person and when necessary either to protect our rights or property including to enforce our Terms of Service, or for us to render the service you have requested.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}>We may also disclose personally identifiable information when required by law, regulation, court order, or in response to a subpoena or litigation discovery request, or in the good faith belief that such action is necessary in order to conform to the edicts of the law or comply with a legal process served on us.  In addition, we will make any legally required disclosures to government authorities and provide notice to you of any breach of security, confidentiality or unauthorized release of personal or private data in accordance with applicable laws, rules and regulations.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">3. Storage and Security</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We employ reasonable measures (both online and offline) to protect the security of information we collect from you.  Such information is housed in secure databases, equipment and servers located in the South Korea and/or in other countries.  The databases, equipment and servers we utilize may be owned by third party providers.  To prevent unauthorized access, loss, or misuse, maintain data accuracy, and ensure the appropriate use of information, we have put in place physical, electronic, and managerial procedures to safeguard and secure the information we maintain.  We use industry-standard technology, such as firewalls, in an effort to protect the confidentiality of your personal information.  Moreover, in addition to password protection offered in connection with your Service account, we encrypt your transmission of sensitive information to us (e.g., account passwords and payment-related identifiable information) via SSL (secured socket layer) protocol in the interest of heightened privacy protection and information integrity.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Although we take reasonable precautions against possible security breaches of our Service, databases, equipment or servers, and records, we cannot guarantee that unauthorized access, hacking, data loss, or other security breaches and factors beyond our control will never take place and result in disclosure of your personal information.  Accordingly, we disclaim any guarantees, warranties or representations relating to maintenance or nondisclosure of any personal information collected from you.  We strongly urge you to take reasonable measures at all times (online and offline) to protect your personal information, including your password and other sensitive information.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">In addition, while we strive to protect your personal information, you should know that information sent over the Internet, whether by e-mail or by using one of our on-line forms, is not necessarily secure against interception.  Therefore, we cannot be responsible for such interception and cannot guarantee the security of such information.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We will investigate, attempt to resolve and take all reasonable steps necessary to ensure that your personal information and data is treated securely and in accordance with this Privacy Policy.    </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}>We will retain your personal information for as long as is necessary to fulfill the purposes for which it was collected or as needed to provide you with Services. We may retain your personal information after you have closed any account you have with us or after we have ceased providing Services to you if retention of your Personal Information is reasonably necessary to comply with our legal obligations, meet regulatory requirements, resolve disputes between members, prevent fraud, cheating or abuse, or enforce this Privacy Policy or any other agreement we may have with a user.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">4. Additional Privacy Policy Terms</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Opt-Out Provision </strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">When we first collect information from you, we will offer you the opportunity to opt-out of having your personal information shared with parties outside of Company (unless otherwise described in this Privacy Policy).  In addition, if you do not want us to send you communications relating to our Services, including, without limitation, announcements, newsletters and promotional materials or offers to participate in surveys, contests or sweepstakes, you can opt-out at the time of registration or information collection.  If, at a later date, you choose to have your name or any other personal information removed from our mailing list, you can do so by emailing (support@rouv.net</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Review, Update, Correct,</strong><strong> or Delete Personal Information</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Generally, you may review, update, correct or delete your personal information collected by or through our Service by logging into your account.  You may also correct factual inaccuracies.  Certain types of personal information that is necessary to check eligibility, such as birth date or age, cannot be deleted, but may be modified with sufficient verification of the new information.  Note that we reserve the right to terminate or delete any registration or promotional entry if we believe the personal information submitted was knowingly false or fraudulent.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">To delete your personal information, you may also email us at (support@rouv.net). We will use commercially reasonable efforts to honor your request.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Please be aware that even after your account is terminated or deleted, some or all of your information may still remain visible to others, including but not limited to any information that has been: (i) incorporated into others user’s content, comments, postings, submissions, cities, resources or other in-game assets; (ii) copied, stored or disseminated by other users; (iii) shared or disseminated by you or others such as in a public posting; or (iv) posted on a third party platform. A request to delete and/or termination of your account will not result in the removal of information collected and already put in aggregate form or information that cannot, in our sole discretion, be removed without undue burden to us. We are not able and/or obligated to remove any of your information from a third party platform.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Moreover, please be aware that even after you delete your account or your account is terminated, your information is not deleted in its entirety from our servers and may not be deleted from servers of the third party platform you use to access our Services. We may, but are not obligated to, retain backup copies of your information, including personal information on our servers or databases (and/or any authorized third party servers or databases we use). Such information may be disclosed pursuant to this Privacy Policy regardless of whether your account is deleted or terminated. Moreover, any third party platform that you use to access the Services may also retain backup copies of your information even after your account is deleted or terminated which may be used and/or disclosed in accordance with their privacy policy.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">To have access to your personal information, you must provide proof of identification such as full name, street address, city/state and zip code, user ID and password, and/or information about your recent activity on our Service. We reserve the right to deny access to any user if we believe there is a question about your identity. And if the burden or expense of providing access to your personal information is disproportionate to the risks to your privacy, or if the legitimate rights of others would be violated, we may decide not to provide access to such information.  Moreover, we may still retain an archived copy of your information in our files as required by law or for legitimate business purposes, including, resolving disputes, enforcing the Terms of Service, and for other technical and legal requirements and constraints related to our Service. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">To manage the information, we receive about you from the SNS where you play our games, you will need to follow the instructions at that SNS for updating your information and changing your privacy settings.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Notification of Changes</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We reserve the right to update and change the terms of this Privacy Policy at any time.  If we decide to update and materially change the terms of our Privacy Policy, we will post those changes in our Services and/or on the applicable Sites, and in the updated Privacy Policy. You should periodically check this Privacy Policy for updates.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">By continuing to access or use the Services after we have posted an updated Privacy Policy or have provided you with notice of a modification, you are agreeing to be bound by the modified Privacy Policy.  If the modified Privacy Policy is not acceptable to you, your only recourse is to cease using the Services.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Links to Third Party</strong><strong> Websites, Services and Offers.</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Our Service may contain links to other websites, services and/or offers from third parties.  We are not responsible for, nor will it be liable to you or any third party for, your interaction with such third parties or the information requests initiated by such third parties or the subsequent use, treatment or dissemination of the information you voluntarily chose to provide to them. You should review the applicable privacy policies and information practices of such third parties carefully before providing personal information to them.  Moreover, if you have any questions or concerns, you should contact the third party directly.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Protection of Children’s Privacy</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Company is committed to providing special protection for the privacy of children who may use our Service.  The Service is not intended for children under the age of 12 and we do not knowingly collect, use or retain personally identifiable information from such children.  If we discover that we have inadvertently collected personal information from such children, we will take all reasonable measures to delete any records of such personal information that come to our attention. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Special Note to Parents</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">If you become aware that your child has provided us with personal information at our Service, we invite you to notify us so that we may delete the information from our records and discontinue any related features or services (see Opt-Out Provision above).  We also urge parents to instruct their children never to give out their real names, addresses or phone numbers without parental permission when using the Internet.  We appreciate your cooperation in assisting us to provide a safe and enjoyable online experience for your children.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Users Outside South Korea</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Company is a South Korea company and Company’s business operations are primarily conducted in South Korea.  We operate our company and administer this Privacy Policy under applicable laws and regulations of the Republic of Korea(“South Korea”).  If you use our Service from outside South Korea, you are thereby consenting for your personal information to be transferred to, stored in and be processed in the South Korea and/or in other countries by the Company and/or its Affiliates in the manner described in this Privacy Policy.  Your consent to this Privacy Policy followed by your submission of your personal information represents your agreement to such transfer, storage and processing of information.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">As described elsewhere in this Privacy Policy, when you submit personal information via our Service, the information is housed in secure databases, equipment and servers located in the South Korea and/or in other countries.  The databases, equipment and servers we utilize may be owned by third party providers.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Users in certain jurisdictions may have a right to access his/her personal information held by the Company and/or its Affiliates.  Your right of access to such personal information can be exercised in accordance with applicable laws, rules and regulations.  Please submit any requests for such access to (support@rouv.net).</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Language</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The controlling language of this Privacy Policy is English.  If you have received a translation into any other language, it has been provided for your convenience only.  The English version of this Privacy Policy shall govern to the extent of any inconsistency between the English version and any translated version.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"><strong>Contact Us</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">If you have any questions, inquiries, requests, complaints, or comments regarding this Privacy Policy, or have other questions or suggestions about our information practices, please contact us via e-mail at (support@rouv.net).</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">© Gravity Co., Ltd.  All rights reserved.</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
