import Layout from "@/components/Layout";
import { useEffect } from "react";

export default function TermsOfService() {
  useEffect(() => { window.scrollTo(0, 0); }, []);
  return (
    <Layout>
      <div className="min-h-screen bg-white dark:bg-[#0a0a0a]">
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white py-12">
          <div className="container">
            <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
            <p className="text-blue-100">Effective Date: July 1, 2026</p>
          </div>
        </div>

        {/* Content */}
        <div className="container py-12">
          <div className="max-w-4xl mx-auto">
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1"></p>
                                    <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Gravity Co., Ltd. ("<u>Company</u>," "<u>we</u>", "<u>us</u>" or "<u>our</u>") maintains these Terms of Service ("<u>TOS</u>") that describes the terms and conditions applicable to the use of our game applications for personal computers and mobile devices and Applications accessible on social networking services (“<u>SNS</u>”) (each, an “Application” and collectively, “<u>Applications</u>”).  Your use of the Applications is subject at all times to these TOS, our privacy policy (“<u>Privacy Policy</u>”) and any additional end user license agreements (the “<u>EULA</u>”) which may apply.  Any inconsistencies between this TOS, the Privacy Policy or any EULA shall be resolved by the Company in its sole and absolute discretion.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><strong>Notwithstanding any provision herein, under any circumstance, the countries embargoed by the United States or the countries set forth on “the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Department of Commerce Denied Persons List or Entity List” shall be clearly excluded from the scope of any services.</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">EACH TIME YOU USE OR ACCESS AN APPLICATION, YOU AGREE TO BE BOUND BY THESE TOS AND REPRESENT THAT YOU HAVE READ AND UNDERSTAND THE RIGHTS, OBLIGATIONS, TERMS AND CONDITIONS SET FORTH HEREIN AND AGREE TO BE LEGALLY BOUND BY THEM.  IF YOU DO NOT UNDERSTAND OR AGREE TO BE BOUND BY (OR CANNOT COMPLY WITH) THESE TOS, DO NOT USE OR ACCESS THE APPLICATIONS.  YOUR CONTINUED ACCESS AND USE OF ANY APPLICATION SHALL BE DEEMED TO CONSTITUTE YOUR AGREEMENT TO BE LEGALLY BOUND BY THESE TOS, AS THEY MAY BE AMENDED FROM TIME TO TIME. ALSO, IF YOU ARE A MINOR, YOU REPRESENT THAT YOUR REGAL GUARDIAN HAS REVIEWED AND AGREED TO THESE TERMS. ANY REFERENCES HEREIN TO “YOU” AND “YOUR” REFER TO BOTH YOU AND SUCH PERSON AND ENTITY ON WHOSE BEHALF YOU ACT, IF ANY. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}>In some instances, both these TOS and separate terms of service, rules, policies or guidelines set forth additional conditions that may apply to an Application, including, without limitation, the Apple iTunes Store Terms and Conditions, the Google Play Terms of Service, Google Terms of Service, Google Business Play Program and Policies and any applicable SNS terms and conditions (collectively, the “Additional Terms”).  To the extent there is a conflict between the TOS and any Additional Terms, the Additional Terms will control unless the Company determines otherwise, in its sole and absolute discretion.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">1. LICENSE</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(a)	<u>License Grant</u>. Subject to the terms and conditions of these TOS, the Privacy Policy and any Additional Terms (each of which are hereby incorporated by this reference), the Company hereby grants to you a limited, non-exclusive, non-transferable and revocable right and license to: (i) download, install and use the subject Applications (excluding source code) on your personal computer and/or mobile device, and (ii) access and use the Application through the subject SNS.  The Company may terminate this license without notice in the event you fail to comply with these TOS, the Privacy Policy or any Additional Terms.  Upon termination of the license, you must immediately cease accessing and using all Applications.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(b)	<u>Limitations</u>.  The license granted to you is subject to the following limitations.  You shall not or permit any other person to:</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(i)	in whole or in part, (1) modify or create any derivative work of the Company Materials (defined below), other user’s User Content or Application, or (2) copy, photocopy, reproduce, translate, disassemble, reverse engineer, decompile, or otherwise attempt to derive source code, underlying ideas, algorithms, structure, or organization of any Application;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(ii)	modify, alter or remove any copyright, patent, confidentiality, trademark and other notices, labels or legends in any Company Materials, other user’s User Content or Application;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(iii)	sell, grant a security interest in or transfer reproductions of any Company Materials, other user’s User Content or Application to other parties in any way not expressly authorized herein; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(iv)	assign, rent, lease, distribute or license any Company Materials, other user’s User Content or Application to others; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(v)	exploit any Company Materials, other user’s User Content or Application, or any of its parts for any commercial purpose;</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(vi)	use any third-party software to modify any Application; </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(vii)	use any Application to access, copy, transfer, transcode or retransmit content in violation of third party intellectual property rights; or</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(viii)	create or maintain, under any circumstance, any unauthorized connections to any Application.  All connections to the Applications may only be made through methods and means expressly approved by the Company.  Under no circumstances will you connect, or create tools that allow you or others to connect, to the proprietary interface or interfaces other than those expressly provided by the Company for public use.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(c)	<u>Additional Agreements</u>.　</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(i)	You agree to use the Applications only in compliance with these TOS, the Privacy Policy, Additional Terms and applicable rules, laws and regulations, including applicable tax laws.   </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(ii)	By accessing and using the Applications, you represent and warrant that you are not prohibited from receiving exports or services under the applicable export laws. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	(iii)	You agree that by accessing and using the Applications you may be exposed to content that you may find offensive, indecent or objectionable and that you access and use the Applications at your own risk. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">	<u>Your failure to comply with the restrictions and limitations listed above and elsewhere in these TOS shall result in immediate (without notice), automatic termination of the license granted hereunder and may subject you to civil and/or criminal liability.  </u></p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>2.</strong><strong style={{paddingTop: '30px'}}>	IP OWNERSHIP</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(a)	<u>Company Materials</u>.  The Company, its licensors and/or certain third parties (as applicable) retain exclusive right, title and interest (including all intellectual property rights) in and to all materials that are part of the Applications (including past, present and future versions) (excluding User Content), including, without limitation: graphics; layout; text; images; audio and/or video; designs; advertising copy; logos; domain names; trade names and marks; and service marks; any and all copyrightable material; the “look and feel”; the compilation, assembly and arrangement of the materials of the Applications; and all other materials or content made available on the Applications (collectively, the “Company Materials”) and such Company Materials are  protected from unauthorized use, copying and dissemination by copyright, trademark, patent, publicity and other laws, rules, regulations and international treaties.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(b)	<u>Trademark Notice</u>.  All words and logos in an Application marked by the ™ or ® symbols are trademarks and service marks of the Company and/or its licensor(s).  All rights are reserved.  All other trademarks and service marks appearing in the Applications are the property of their respective owners.  All rights are reserved.  Use of any of our trademarks, service marks or names as “metatags” for any purpose other than as expressly authorized in these TOS is strictly prohibited. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(c)	<u>Application</u>.  The Company and/or its licensors retain exclusive right, title and interest (including all intellectual property rights) in and to all Applications, copies thereof, and all error corrections, bug-fixes, patches, updates, derivative works, improvements, modifications thereto (whether made by the Company, its licensors, you, or otherwise), any titles, computer code, themes, objects, characters, character names, stories, dialog, catch phrases, locations, concepts, artwork, character inventories, structural or landscape designs, animations, sounds, musical compositions, audio-visual effects, storylines, character likenesses, methods of operation, moral rights, in-game currency, in-game accessories or incentive points, any related documentation, and “applets” incorporated into the Applications.  The rights described in the foregoing sentence are the copyrighted work of the Company and/or its licensors and are protected by the copyright laws of the Republic of Korea( “South Korea”), international copyright treaties and conventions, and/or other applicable laws.  The Application may contain certain licensed materials, and the licensors of those materials may enforce their rights in the event of any violation of this TOS.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(d)	<u>Third Parties</u>.  The Applications may be incorporated into, and may incorporate itself, software and other technology owned and controlled by third parties. Any such third party software or technology that is incorporated in the Applications falls under the scope of these TOS. Any and all other third party software or technology that may be distributed together with the Applications will be subject to you explicitly accepting a license agreement with that third party. You acknowledge and agree that you will not enter into a contractual relationship with the Company regarding such third party software or technology and you will look solely to the applicable third party and not to the Company to enforce any of your rights.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(e)	<u>No Additional Rights</u>.  Only those licenses expressly set forth in these TOS are granted.  No other licenses are granted under these TOS, whether by implication, estoppel, course of conduct, or otherwise.  Nothing in these TOS is intended to transfer any of the right, title and interest (including all intellectual property rights) from the Company and/or its licensors to you or any third party.  If you are ever inadvertently or erroneously held or deemed to be the owner of any such rights, you agree to assign and hereby irrevocably assign to the Company or its licensors, as the case may be, all such rights as of the effective date of these TOS, and agree to execute all documents to implement and confirm the letter and intent of the foregoing.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(f)	<u>In-Game Items</u>.  YOU HEREBY ACKNOWLEDGE AND AGREE THAT YOU ARE ONLY LICENSED THE RIGHTS TO ACCESS AND USE THE APPLICATIONS, AND AS THE COMPANY EITHER OWNS, OR HAS LICENSED, ALL OF THE COMPANY MATERIALS, APPLICATIONS AND OTHER CONTENT WHICH APPEAR IN THE APPLICATIONS, THE COMPANY DOES NOT RECOGNIZE ANY PROPERTY CLAIMS OUTSIDE OF THE APPLICATIONS, OR THE PURPORTED SALE, GIFT OR TRADE IN THE “REAL WORLD” OF ANYTHING RELATED TO THE APPLICATIONS. SPECIFICALLY, ALTHOUGH YOU MAY ACQUIRE, CREATE, DESIGN, OR MODIFY VIRTUAL IN-GAME CURRENCY (I.E., COINS, CARDS, CASH, TOKENS, POINTS, ETC.), IN-GAME ACCESSORIES, INCENTIVE POINTS OR OTHER GOODS OR SERVICES FOR USE IN THE APPLICATIONS (COLLECTIVELY, “VIRTUAL ITEMS”), YOU AGREE THAT YOU WILL NOT GAIN ANY OWNERSHIP INTEREST WHATSOEVER IN ANY SUCH VIRTUAL ITEMS. ACCORDINGLY, YOU MAY NOT SELL SUCH VIRTUAL ITEMS FOR “REAL” MONEY OR EXCHANGE VIRTUAL ITEMS, AND DOING SO MAY LEAD TO THE IMMEDIATE (WITHOUT NOTICE), AUTOMATIC TERMINATION OF THE LICENSE GRANTED HEREUNDER, AND MAY SUBJECT YOU TO CIVIL AND/OR CRIMINAL LIABILITY. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>IMPORTANT NOTICE</u>:  The Company does not recognize or condone any outside service that may be used for the exchange of Virtual Items that you may accumulate as a result of accessing or using the Applications. This includes the exchange of any Virtual Items on third party services including eBay™ or Yahoo!™ Auctions. We do not assume any responsibility for, and will not support, such transactions. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm" style={{paddingBottom: '30px'}}>(g)	ANY PURCHASES OF VIRTUAL ITEMS DO NOT ENTITLE YOU TO SERVICE IN THE EVENT THAT THE COMPANY CEASES TO OFFER THE APPLICATIONS FOR ANY REASON, IS ACQUIRED BY A THIRD PARTY OR FILES A NOTICE OF BANKRUPTCY WITH ANY COURT.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1">3. ACCOUNT, FEES AND REFUNDS</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You may currently access the Applications without establishing a user account (“<u>Account</u>”).  We may, however, in the future require Application users to register and establish an Account.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You may allow our Services to interact with a third party social network or platform, which will provide data about you to us. If you choose to connect to one of our Websites or Applications through a third-party social network such as Facebook or Game Center (for iOS devices), we may collect personal Information from your profile on such third-party social networks, such as your name, username, and photographs. You should ensure that you read their terms of service and privacy policies to understand how they treat your data and what data they might share with us.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You must pay the applicable fee for each Application and any available Virtual Items.  Where applicable and subject to the applicable payment terms and conditions, you can order Virtual Items by visiting the purchase page in the Application, provide your credit card, PayPal or other applicable billing method information.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">In addition to the foregoing, you hereby acknowledge and agree that you shall solely be responsible for and bear all telecommunication expenses, including, telephone charges, Internet connection charges and electricity charges, arising out of your access and use of the Applications.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Subject to technical problems and revisions to payment policies which may be instituted by the Company and partners at any time without notice, you may pay for any applicable fees and other charges by major credit card or such other methods expressly authorized in writing by the Company and its partners. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Any dispute arising between you and any third party payment provider (including a credit card company) shall be resolved directly between you and such third party provider.  Under no circumstances shall Company be liable for any obligations incurred by you to such third party provider in connection with your access and use of the Applications.  You agree to indemnify, defend and hold harmless Company, its licensors, affiliates, employees, officers, and directors from all claims for liabilities, losses and expenses, including reasonable attorneys’ fees, from third parties arising from such dispute.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You have the right to cease accessing and using any Application at any time. You understand and agree that unless otherwise expressly provided for in this TOS, the cessation of access and use of the Applications is your sole right and remedy with respect to any dispute, including, but not limited to, any related to, or arising out of: (i) any term of this TOS or the Company’s enforcement or application of this TOS, (ii) the Company Materials and other content available through the Applications, (iii) your ability to access and/or use the Applications and/or (iv) the amount or type of fees, surcharges, applicable taxes, billing methods, or any change to the fees, applicable taxes, surcharges or billing methods.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Without limiting any other remedies, we may limit, suspend, terminate, modify or delete your  access to the Applications (or any portion thereof) at any time if you are, or we suspect that you are, failing to comply with any of this TOS, the Privacy Policy or Additional Terms with or without notice to you.  If the Company terminates your access to the Applications, you may lose your user ID as well as any benefits, privileges, Virtual Items and User Content associated with the subject Application, and we are under no obligation to compensate you for any such losses or results.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">Moreover, no online time or other credits will be provided to you or converted to cash or other form of reimbursement, and you will have no further access to the subject Applications (including all Virtual Items).   Moreover, you will not have the right to transfer, sell, or assign any Virtual Items to anyone else.  Under no circumstances shall Company be responsible for storing any User Content and other information following suspension, termination, modification or deletion of your access to the Applications.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">WE RESERVE THE RIGHT TO TERMINATE YOUR ACCOUNT WITHOUT ANY NOTICE if your account has not been accessed for more than 3 years. In such event, you will no longer be able to access and/or use the Services using the terminated account. Any Virtual Money and/or Virtual Goods associated with the terminated account will also be deleted, and no refund will be offered to you with respected to such Virtual Money or Virtual Goods deleted.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">We reserve the right to stop offering and/or supporting an Application at any time, at which time your license to access and use the specific Application will automatically be terminated without further action.  In such event, we shall not be required to provide refunds, benefits or other compensation to you.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">There may also be times when our Services or any part thereof are not available for technical or maintenance related reasons, whether on a scheduled or unscheduled basis. You agree that Company has no responsibility and is not liable for unavailability of the Services or any part thereof, any loss of materials, data, transactions or any other information or materials caused by such system outages, or other losses whatsoever resulting from such system outage.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm"><u>ALL FEES AND CHARGES YOU INCURRED IN PURCHASING VIRTUAL ITEMS ARE NON-REFUNDABLE.  YOU ACKNOWLEDGE AND AGREE THAT WE ARE NOT REQUIRED TO PROVIDE A REFUND TO YOU FOR ANY REASON, AND THAT YOU WILL NOT RECEIVE ANY MONEY OR OTHER COMPENSATION FOR UNUSED VIRTUAL ITEMS WHEN WE STOP OFFERING AND/OR SUPPORTING ANY APPLICATION AVAILABLE TO YOU.  </u></p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>4. USER CONTENT</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Company does not solicit submissions, creative materials, ideas or suggestions other than those the Company may specifically request.  Any communications or materials you transmit to the Company by e-mail or otherwise including, without limitation, data, questions, feedback, comments, ideas, images, writings, music, sounds, audiovisual effects, artwork, design elements, graphics, suggestions, concepts, biographical information, notes or chat or message postings, will be treated as non-confidential and non-proprietary except as otherwise described in the Privacy Policy.  As part of an Application, the Company may invite you to participate in blogs, message boards, contests, sweepstakes, forums and other functionality and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute or broadcast content and materials to the Company and/or to or via an Application, including, without limitation, text, writings, photographs, graphics, comments, suggestions or personally identifiable information or other material (collectively, excluding Company Materials not created by you, “<u>User Content</u>”). You agree that your User Content is wholly original with you and you exclusively own the rights to your User Content, including the right to grant all of the rights and licenses in these TOS without the Company incurring any third party obligations or liability arising out of its exercise of the rights thereto granted herein by you.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You hereby grant to the Company the unrestricted, unconditional, unlimited, worldwide, irrevocable, perpetual, fully-paid and royalty-free right and license to host, use, copy, distribute, reproduce, disclose, sell, re-sell, sub-license, display, perform, transmit, publish, broadcast, modify, delete, make derivative works from, retitle, reformat, translate, archive, store, cache or otherwise exploit in any manner whatsoever, all or any portion of your User Content to which you have contributed, for any purpose whatsoever, in any and all formats; on or through any and all media, software, formula or medium now known or hereafter known; and with any technology or devices now known or hereafter developed and to advertise, market and promote same.  You further agree that the Company is free to use any ideas, information, concepts, know-how or techniques contained in any User Content you send to the Company, for any purposes whatsoever, including, without limitation, developing, producing, marketing and otherwise exploiting products and/or services using such User Content, and without remuneration of any kind. You further perpetually and irrevocably grant the Company the unconditional right to use and exploit your name, persona and likeness included in any User Content and in connection with any User Content, without any obligations to you.  Except as prohibited by law, you waive any rights of attribution and/or any so-called moral rights you may have in any User Content you submit, even if such User Content is altered or changed in a manner not agreeable to you.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The  Company has no obligation to monitor or enforce your intellectual property rights to your User Content but has the right to protect and enforce its licensed rights to your User Content, including, without limitation, by bringing and controlling actions in your name and on your behalf (at the Company’s cost and expense, to which you hereby consent and irrevocably appoint the Company as your attorney-in-fact, with the power of substitution and delegations, which appointment is coupled with an interest).  You also agree and understand that the Company is not obligated to use User Content and that you will not receive any additional consideration or compensation for your User Content or for any exploitation thereof. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You acknowledge and agree that your communications with other users via any channel of communication in an Application are public and not private, and that you have no expectation of privacy concerning your access and use of an Application.  You acknowledge that personal information that you communicate in an Application may be seen and used by others and result in unsolicited communications, therefore we strongly encourage you not to disclose any personal information about yourself in your public communications in an Application.  You are solely responsible for these communications and their legality under all applicable laws and regulations.  Company is not responsible for information that you choose to communicate to other users in an Application, or for the actions of other users. For information regarding Company’s use of information collected in connection with the Applications, please refer to the Privacy Policy.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>5.	ONLINE CONDUCT</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You agree that you will be personally responsible for your access and use of the Applications and for all of your User Content and online activity in connection with the Applications, and that you will indemnify and hold harmless the Company, its licensors, affiliates, employees, officers, and directors from all claims for liabilities, losses and expenses, including reasonable attorneys’ fees, from third parties arising from such use, User Content and activity. Specifically, you agree to comply with these TOS, all applicable laws, rules and regulations governing the disclosure and use of third party property, including, without limitation, any and all intellectual property rights. Moreover, you agree not to engage in any of the following:</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(a)	Post, transmit, promote, or distribute illegal content. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(b)	Harass, threaten, abuse, disparage, libel, slander, embarrass, or engage in any other disruptive behavior involving another user or Company or affiliate’s employee or agent. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(c)	Transmit or facilitate distribution of content that is harmful, abusive, racially or ethnically offensive, vulgar, sexually explicit, defamatory, infringing, invasive of personal privacy or publicity rights, or in a reasonable person's view, objectionable. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(d)	Infringe upon the intellectual property rights of Company or any third party. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(e)	Alter, delete or cancel any user profile information or User Content. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(f)	Disrupt the flow of chat in chat rooms with vulgar language, abusiveness, hitting the return key repeatedly or inputting large images so the screen goes by too fast to read, use of excessive shouting, using ALL CAPS in an attempt to disturb other users, “spamming” or flooding or posting repetitive text. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(g)	Impersonate another person, indicate that you are a Company or affiliate employee or agent, or attempt to mislead users by indicating that you represent Company or any of Company’s licensors or affiliates. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(h)	Attempt to get a user ID, password, or other user information, or any other private information from a user.   <u>Company employees will NEVER ask for your password.  DO NOT give your password, secret answers, or billing information out to anyone. </u></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(i)	Upload any content that you do not own or have the right to freely distribute. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(j)	Engage in or promote or encourage any illegal or fraudulent activity including hacking, cracking or distribution of counterfeit software, or identity theft. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(k)	Upload files or display URLs that contain a virus or corrupted data. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(l)	Post messages for any purpose other than personal communication, including, without limitation, advertising, promotional materials, chain letters, pyramid schemes.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(m)	Make any commercial use of the Applications, including using the Applications as an Internet dating service website, use at a cyber café, computer gaming center or any other location-based site without the express written consent of Company.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(n)	Improperly use in game support or complaint buttons or make false reports to Company. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(o)	Use or distribute “auto” software programs, “macro” software programs or other “cheat utility” software program or applications. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(p)	Modify, reproduce, distribute, delete or create derivative works of the Applications, Company Materials or any User Content displayed therein, or any component thereof.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(q)	Attempt (or authorize, encourage or support others’ attempts) to circumvent, reverse engineer, decrypt, break or otherwise alter or interfere with the Applications or any component thereto.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(r)	Solicit or attempt to solicit, and post or communicate any user’s personal information. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(s)	Interfere with, hack into or decipher any transmissions to or from the servers running the Applications. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(t)	Exploit any bug in any Application or in any Company product to gain unfair advantage in a game or exploit it for commercial purposes.  You agree not to communicate the existence of any such bug (either directly or through the public posting) to any other user or third party. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(u)	Attempt to play any game on or through any service that is not controlled or authorized by Company.  You will not participate in any online service that provides online features or game play for a game that is not authorized by Company. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(v)	Do anything that interferes with the ability of other users to enjoy playing a game and using the Applications or that materially increases the expense or difficulty of Company in maintaining the Applications for the enjoyment of all its users. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(w)	Sell, purchase, gift or exchange Virtual Items for “real” money.  </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(x)	Copy, sell, assign, lease, license or grant a security interest in the Applications or any part thereof (including Company Materials and Virtual Items).</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(y)	Modify or remove any copyright, patent, confidentiality, and other notices, labels or legends in the Applications.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(z)	Host, provide or develop matchmaking services for a game or intercept, emulate or redirect the communication protocols used by Company or its licensors in any way, including, without limitation, through protocol emulation, tunneling, packet sniffing, modifying or adding components to a game, use of a utility program or any other techniques now known or hereafter developed, for any purpose, including, but not limited to, unauthorized network play over the Internet, network play utilizing commercial or non-commercial gaming networks or as part of content aggregation networks.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(aa)	Attempt to gain and maintain any unauthorized connections to an Application.  All connections to a game and/or the Applications may only be made through methods and means expressly approved by Company.  Under no circumstances will you connect, or create tools that allow you or others to connect, to a game’s proprietary interface or interfaces other than those expressly provided by Company for public use. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(bb)	Interfere or attempt to interfere with the proper functioning of the Applications or connect to or use the Applications in any way not expressly permitted by this TOS.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(cc)	Use the Applications in connection with any violation of any applicable laws, rules or regulations, or do anything that promotes the violation of any applicable laws, rules or regulations.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">If you encounter another user who is violating any of the items described in the Online Conduct list above, please report them to (support@rouv.net)</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>6.	MODIFICATIONS</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(a)	<u>Terms of Service</u>.  The Company may, from time to time, modify, amend, or supplement these TOS and post those changes on the TOS page. Such modifications or supplements shall be effective immediately upon posting in the Applications. You are responsible for periodically checking the Applications for changes to the TOS. If you do not agree to be bound by (or cannot comply with) the TOS as modified or supplemented, you agree that your sole remedy is to cease using the Applications.  Your continued access and use of any Application constitutes your agreement to be bound by the modified TOS.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(b)	<u>Changes</u>.   The Company reserves the exclusive right and may, at any time and without notice and liability to you, modify, supplement, suspend or discontinue (collectively, “Changes”) the Applications, whether temporarily or permanently, in whole or in part.  Any such Change shall be effective immediately upon notice by posting on the Applications or these TOS, or by any other method of notice the Company deems appropriate.  Any access or use of the Applications after such notice of Change, constitutes acceptance by you of such Change.  Temporary interruptions in the availability of the Applications may occur from time to time as normal events. You agree that neither the Company nor any of its affiliates, licensors, agents, or employees is liable to you or any third party for any revision, supplement, suspension, or discontinuation of the Applications, and termination of any license.   The Applications may include technical inaccuracies, typographical errors or may enable you to access or download harmful or malicious code introduced onto the Internet by third parties. The Applications are made available internationally and may contain references to products, programs and services of the Company /or its licensors that are not available in your location. Such references do not imply that the Company or its licensors intend to make available such products, programs or services in your location. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">(c)	<u>Applications</u>.  The Company and/or its licensors may deploy or provide patches, updates, upgrades, error corrections, bug-fixes, modifications and additional features or functions to any Application that must be installed for you to continue accessing and using the Application.  The Company and/or its licensors may upgrade or update the Application remotely, including, without limitation, the Application residing on your machine, without your knowledge or consent, and you hereby grant to the Company and its licensors your consent to deploy and apply such patches, updates, upgrades, error corrections, bug-fixes, and modifications, and additional features or functions to the Applications.  The Company has no obligation to make available to you any subsequent versions of the Applications.  You may have to enter into a renewed version of these TOS, in the event you want to download, install or use a new version of the Applications.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>7.</strong><strong style={{paddingTop: '30px'}}>	DISCLAIMER OF WARRANTIES</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">YOU EXPRESSLY AGREE THAT THE USE OF THE APPLICATIONS AND THE INTERNET IS AT YOUR SOLE RISK.  THE APPLICATIONS, THIRD-PARTY SERVICES AND PRODUCTS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS FOR YOUR USE, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTIBILITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE. THE COMPANY PROVIDES THE APPLICATIONS ON A COMMERCIALLY REASONABLE BASIS AND DOES NOT GUARANTEE THAT YOU WILL BE ABLE TO ACCESS OR USE THE APPLICATIONS AT TIMES OR LOCATIONS OF YOUR CHOOSING, OR THAT THE COMPANY WILL HAVE ADEQUATE CAPACITY FOR THE APPLICATIONS AS A WHOLE OR IN ANY SPECIFIC GEOGRAPHIC AREA. YOUR ACCESS AND USE OF THE APPLICATIONS IS AT YOUR OWN DISCRETION AND RISK AND YOU ARE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER OR MOBILE DEVICE, OR LOSS OF DATA THAT RESULTS FROM SUCH ACCESS OR USE.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>8.</strong><strong style={{paddingTop: '30px'}}>	LIMITATIONS OF LIABILITIES</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">YOU ACKNOWLEDGE AND AGREE THAT YOUR SOLE AND EXCLUSIVE REMEDY FOR ANY DISPUTE WITH THE COMPANY OR ITS LICENSORS IS TO STOP ACCESSING AND USING THE APPLICATIONS. YOU ACKNOWLEDGE AND AGREE THAT IN NO EVENT WILL THE COMPANY, ITS LICENSORS OR ITS AFFILIATES BE LIABLE FOR ANY ACT OR FAILURE TO ACT BY THEM OR ANY OTHER PERSON REGARDING CONDUCT, COMMUNICATION OR CONTENT ON THE APPLICATIONS OR THE ACCESS OR USE THEREOF. MOREOVER, IN NO CASE SHALL THE COMPANY’S OR ITS LICENSORS', AFFILIATES’, EMPLOYEES', OFFICERS', OR DIRECTORS' (COLLECTIVELY, “<u>COMPANY AFFILIATES</u>") LIABILITY TO YOU EXCEED THE AMOUNT THAT YOU PAID TO THE COMPANY FOR THE SUBJECT APPLICATION.  FURTHERMORE, IN NO CASE SHALL THE COMPANY, ITS LICENSORS OR AFFILIATES BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOSS OF PROFITS, DATA, USE, GOODWILL, BUSINESS INTERRUPTION, OR OTHER INTANGIBLE LOSS) ARISING FROM YOUR ACCESS AND USE OF ANY APPLICATION, THE INTERNET OR FOR ANY OTHER CLAIM RELATED IN ANY WAY TO YOUR ACCESS AND USE OF OR USERSHIP, WHETHER BASED ON WARRANTY, PRODUCT LIABILITY, CONTRACT, TORT OR ANY OTHER LEGAL THEORY AND WHETHER OR NOT THE COMPANY OR ANY COMPANY AFFILIATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH JURISDICTIONS, THE COMPANY’S AND COMPANY AFFILIATES' LIABILITY SHALL BE LIMITED TO THE FULL EXTENT PERMITTED BY LAW. THE COMPANY DOES NOT ENDORSE, WARRANT OR GUARANTEE ANY THIRD PARTY PRODUCT OR SERVICE OFFERED THROUGH ANY APPLICATIONAND WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>9. LINKS WITH OTHER SITES</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">For the convenience of our user, an Application may provide certain links to websites provided by third parties. The Company is not responsible for the content of any other website linked to or from an Application.  If you link to another website, you leave the subject Application and you do so entirely at your own risk.  The Company provides links from an Application to other sites solely as a convenience to you and in no way should this be interpreted as a referral or endorsement of any content, sponsor or owner of any other website. THE COMPANY DISCLAIMS ALL WARRANTIES, CONDITIONS OR OTHER TERMS EXPRESS OR IMPLIED AS TO ANY SUCH LINKED WEBSITE, INCLUDING, WITHOUT LIMITATION, AS TO ACCURACY, OWNERSHIP, VALIDITY OR LEGALITY OF ANY CONTENT OF A LINKED WEBSITE. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>10. INDEMNIFICATION</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You agree to defend, indemnify and hold harmless the Company and its licensors, affiliates, employees, officers, and directors from all claims for liabilities, losses and expenses, including reasonable attorneys' fees and costs, from third parties arising from: (a) any breach of these TOS, the Privacy Policy, Additional Terms or any applicable rules, laws or regulations, whether or not referenced herein, (b) in connection with your access and use of the Applications, (c) violation of any rights of any third party, (d) use or misuse of the Applications, or (e) communication spread by means of the Applications.  The Company reserves the right to assume the exclusive defense and control of any matter subject to indemnification by you. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>11. GOVERNING LAW</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Applications are made accessible, operated and controlled from the Company in South Korea.   It can be accessed from various countries of the world.  The laws of the South Korea, without regard to conflicts of law provisions, will apply to all matters arising out of or in connection with the Applications and your access use thereof.  By accessing and using the Applications, you submit and consent to the exclusive jurisdiction of the Seoul Western District Court located in Seoul, South Korea with respect to any dispute or cause of action arising out of or in connection with these TOS, the Privacy Policy, Additional Terms and/or your use of any Application. </p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You are solely responsible for your interactions with other users of the Applications.  If you have a dispute with one or more users of any Application, you release us (and its licensors, affiliates, employees, officers, directors, contractors, agents, third party suppliers, licensors and third party partners) from claims, demands and damages (actual and consequential) of every kind and nature, known or unknown, arising out of or in connection with such disputes.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>12. INJUNCTIVE RELIEF</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">You acknowledge that the rights granted and obligations made hereunder to the Company are of a unique and irreplaceable nature, the loss of which shall irreparably harm the Company and which cannot be replaced by monetary damages alone so that the Company shall be entitled to injunctive or other equitably relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you.  You irrevocably waive all rights to seek injunctive or other equitable relief and agree to limit your claims to claims for money damages (if any). </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>13. VOID WHERE PROHIBITED</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The information provided through the Applications are not intended for distribution to or use by any person in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject the Company to any registration requirement within such jurisdiction or country.   The Company makes no representation or warranty that any material on the Applications is lawful in every jurisdiction from which such content can be accessed, or is available for use in all jurisdictions.  If you access or use the Applications, you are responsible for compliance with all applicable local laws.  THE APPLICATIONS ARE INTENDED FOR USE BY PERSONS AGED 12 AND OVER.  BY ACCESSING AND USING ANY APPLICATION, YOU REPRESENT AND WARRANT THAT YOU ARE 12 OR OLDER, AND THAT YOU AGREE TO AND TO ABIDE BY ALL OF THE TERMS AND CONDITIONS OF THESE TOS, THE PRIVACY POLICY AND ADDITIONAL TERMS.  MOREOVER, IF YOU ARE BETWEEN 12 AND 18 YEARS OF AGE, YOU REPRESENT AND WARRANT THAT YOU HAVE YOUR PARENT OR LEGAL GUARDIAN’S PERMISSION TO ACCESS AND USE THE APPLICATIONS.  IF YOU ARE UNDER THE AGE OF 12 OR BETWEEN THE AGE OF 12 AND 18 BUT DID NOT HAVE YOUR PARENT OR LEGAL GUARDIAN’S PERMISSION TO THE ACCESS AND USE THE APPLICATIONS, THE COMPANY MAY IMMEDIATELY (WITHOUT NOTICE) TERMINATE THE LICENSE GRANTED HEREUNDER. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}><strong style={{paddingTop: '30px'}}>14. COMPLAINTS, NOTICE AND CONTACT INFORMATION</strong></p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Company takes claims of infringement of intellectual property rights and violation of rights of privacy or publicity very seriously.  If you believe that any of the material that is or was in any Application infringes or has infringed any rights, including copyrights or trademarks, owned by you, or by an owner for which you are authorized to act, please contact us at (support@rouv.net)</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>15. PRIVACY POLICY</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Company is committed to respecting your privacy and the confidentiality of your personal data.  The Privacy Policy sets out how the Company may use your personal data, the traffic data and the content contained in your communication(s).  If you object to your information being used in the way set out in the Privacy Policy, your sole remedy is to cease accessing and using the Applications.</p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>16. NOTICE</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">In the event the Company decides, in its sole and absolute discretion, to give notice to a user regarding the termination of the licenses granted herein, revisions to payment policies, or any Changes, it may do so via email, telephone call, posting in the Applications or these TOS, or such other method of notice the Company deems appropriate.  Where Company decides to give such notice, any access or use of any Applications after delivery of such notice constitutes acceptance by you of the noticed action.  </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>17. RESTRICTIONS</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">The Applications may be subject to international rules that govern the export of software. You shall comply with all applicable international and national laws that apply to the Applications as well as end-user, end-use and destination restrictions issued by national governments. </p>
            <p className="text-sm font-bold text-foreground dark:text-white mt-4 mb-1" style={{paddingTop: '30px'}}>18. MISCELLANEOUS</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">If any provision of these TOS is held to be invalid or unenforceable, that provision will be deemed to be restated to reflect as nearly as possible the original intention in accordance with applicable law, and the remainder of the TOS will remain in full force and effect. The TOS, the Privacy Policy and Additional Terms (if applicable) constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter.  Nothing in the foregoing sentence shall exclude or restrict the liability of you arising out of fraud or fraudulent misrepresentation.  Any waiver of any provision of the TOS will be effective only if in writing and signed by the Company.  The failure of party to assert any right under these TOS shall not be considered a waiver of that party's right and such right will remain in full force and effect. In addition, the TOS, any Additional Terms and the Privacy Policy, including the Company’s enforcement of those policies, are not intended to confer, and do not confer, any rights or remedies upon any person.  The original English version of these TOS may have been translated into other languages.  In the event of inconsistency or discrepancy between the English version and any other language version, the English language version shall prevail.  You are not allowed to assign the TOS or any rights hereunder.  The Company is allowed at its sole discretion to assign the TOS or any rights hereunder to any third party, with giving prior notice to you.</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm text-center">* * * * * *</p>
            <p className="text-foreground/80 dark:text-white/80 mb-3 leading-relaxed text-sm">If you have any questions, complaints, or comments regarding these TOS, or have other questions or suggestions about the Applications, please contact us via e-mail at (support@rouv.net)</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
